services:
  redis:
    container_name: "redis"
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    container_name: "flask"
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      - redis
      - rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    container_name: "worker"
    build: .
    command: celery -A app.celery worker --loglevel=info -Q default
    volumes:
      - .:/code
    depends_on:
      - redis
      - web

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/locust/locustfile.py
    command: -f /locust/locustfile.py
    depends_on:
      - web

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  redis_data: